webapp/config/routes.rb
Rails.application.routes.draw do
  resources :users, :pop
  post 'pop/create' => 'pop#create'
  root 'users#index'

end

webapp/app/models/pop.rb
class Pop
  include Neo4j::ActiveNode

  property :name
  property :X, type: Float
  property :Y, type: Float
  property :Z, type: Float

  has_many :both, :has, type: :pop, model_class: Pop

end

webapp/app/models/user.rb
class User < ActiveRecord::Base

end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

webapp/app/controllers/pop_controller.rb
class PopController < ApplicationController
  # before_action :set_pop, only: [:show, :edit, :update, :destroy]
  # GET /pop
  def index
    # @pops = Pop.all
    # respond_to do |format|
    #   valid = %w(pop)
    #   if valid.include?(params[:path])
    #     # @pops = Pop.all
    #     format.html{ render :template => File.join('pop', params[:path]) }
    #   else
    #     render :file => File.join(Rails.root, 'public', '404.html'),
    #            :status => 404
    #   end
    # end
  end

  def new
    if request.post?
      # @pop = Pop.new { name: params[:name], X: params[:X], Y: params[:Y], Z: paramas[:Z] }
      # format.json { render json: }
    end
  end

  def show
    @pop = Pop.find(params[:id])

    respond_to do |format|
      format.json { render :json => @pop }
    end
  end
  # POST /pop
  # POST /pop/create
  def create
    @pop = Pop.new(pop_params)
    respond_to do |format|
      format.json { render :json =>{}, status: :created }
      @pop.save
    end
  end

  def destroy
    @pop.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Pop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pop
      @pop = Pop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pop_params
      params.require(:pop).permit(:name, :X, :Y, :Z)
    end
end

webapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def login
    email = params[:user][:email]
    pass = params[:user][:pass]
    user = User.auth(email,pass)
    if user
      session[:user_id] = user.id
      redirect_to :root
    else
      #error.now[:error] = 'Email/password is wrong. Please try again.'
    end
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :nick, :pass_hash, :pass_salt)
    end
end

webapp/app/controllers/webgl_controller.rb
class WebglController < ApplicationController
  # layout 'webgl'
  # cache :show
  def show
    valid = %w(webgl)
    if valid.include?(params[:path])
      render :template => File.join('webgl', params[:path])
    elsif params?

    else
      render :file => File.join(Rails.root, 'public', '404.html'),
             :status => 404
    end
  end
  def index

  end
  def test
    render js: 'alert("testing");'
  end
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/helpers/pop_helper.rb
module PopHelper
end

webapp/app/helpers/users_helper.rb
module UsersHelper
end

webapp/app/helpers/webgl_helper.rb
module WebglHelper
end

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %> 
    <%= javascript_include_tag "http://webplayer.unity3d.com/download_webplayer-3.x/3.0/uo/UnityObject2.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="fixed">
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
    <ul class="title-area">
	    <li class="name">
	    <h1><a href="/">Triviumer</a></h1></li></ul>
    <section class="top-bar-section">
	    <ul class="right">
		    <li><a href="info">About Trivium</a></li>
		    <li class="divider" />
	    	<li class="has-dropdown">
			<a href="users">
<% if current_user %><%= current_user.username %><% else %>Guest<% end %>
			</a>
			<ul class="dropdown">
				<li><a href="users/login">Login</a></li>
				<li><a href="users/new">Join</a></li>
<%if current_user %>
				<li><a href="users/logout">logout</a></li>
<% end %>
			</ul>
		</li>
		<li><a href="pop" class="button expand">Jump in</a></li>
	</ul>	
  </nav></div>
    <%= yield %>
  </body>
</html>

webapp/app/views/pop/b.index.html.erb
<% if notice %>
<div id="notice" class="alert-box"><%= notice %></div>
<% end %>
<h1>Listing Pops</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>Created date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pops.each do |pop| %>
      <tr>
        <td><%= pop.name %></td>
        <td><%= pop.X %></td>
        <td><%= pop.Y %></td>
        <td><%= pop.Z %></td>
        <td><%= pop.created_at %></td>
        <td><%= link_to 'Show', pop %></td>
        <td><%= link_to 'Edit', edit_pop_path(pop) %></td>
        <td><%= link_to 'Destroy', pop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new pop', new_pop_path %>

webapp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert-box">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nick %><br>
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :pass_hash %><br>
    <%= f.text_field :pass_hash %>
  </div>
  <div class="field">
    <%= f.label :pass_salt %><br>
    <%= f.text_field :pass_salt %>
  </div>
  <%= f.submit 'Agree terms', class:'button success' %>
  <%= f.submit 'Clear', :type=>'reset', class:'button secondary' %>
<% end %>

webapp/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

webapp/app/views/users/index.html.erb
<% if notice %>
<div id="notice" class="alert-box"><%= notice %></div>
<% end %>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Nick</th>
      <th>Joined date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.nick %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Join as user', new_user_path %>

webapp/app/views/users/new.html.erb
<h1>Join as user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

webapp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Nick:</strong>
  <%= @user.nick %>
</p>

<p>
  <strong>Pass hash:</strong>
  <%= pop.pass_hash %>
</p>

<p>
  <strong>Pass salt:</strong>
  <%= @user.pass_salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>